function generateMarkdown(answers) {
  return `
<h1 align="center">${answers.projectTitle} </h1>
    
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
    
 ## Description
🔍 ${answers.description}
    
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
    
 ## Installation
${answers.installation}
    
## Usage
${answers.usage}
    
## License
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
 
This application is covered by the ${answers.license} license. 
    
## Contributing
 ${answers.contributing}
    
## Tests
${answers.tests}
    
## Questions
 ${answers.questions}

Find me on GitHub: [${answers.username}](https://github.com/${answers.username})

Email me with any questions: ${answers.email}
    
This README was generated by [ReaMe-generator](https://github.com/kasaipreston)) 
`;
}

module.exports = generateMarkdown;